addSbtPlugin("io.spray" % "sbt-revolver" % "0.8.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.0-M7")
addSbtPlugin("com.waioeka.sbt" % "cucumber-plugin" % "0.0.2" )
addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "0.11.0")
